name: python-workflo-test
on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.11
    - name: install python package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    -  run: echo "${{secrets.MY_PASSWORD}}" | sudo -S systemctl restart nginx
    - run: echo "uvicorn main:app" > runfile.sh
      shell: bash
   
    - run: pm2 restart all

    
    
      
